### ISSUE TITLE
Read vcc

### ISSUE THREAD

**Issue by Dylantje** [n3roGit/MySensors_n3ro#2]
Dear..
I try you sketches... looking great..
Only i got a error:
C:\Users\DM_PC\Desktop\Mysensors 23-2-2015\GitHub.appref-ms\GitHub.appref-ms.ino:2:21: fatal error: readVcc.h: No such file or directory

 #include <readVcc.h>

Where can i find this ?

**Comment by n3roGit** [comment]
https://github.com/sweebee/Arduino-home-automation/tree/master/libraries/readVcc
