### ISSUE TITLE
dear...

### ISSUE THREAD

**Issue by Dylantje** [n3roGit/MySensors_n3ro#3]

**Comment by Dylantje** [comment]
Dear,..
Like your sketches!!
Is it perhaps a option to implement this:
http://playground.arduino.cc/Learning/ArduinoSleepCode
I do not undertsnad a thing of this only i read that this option saves a lot of battrty

**Comment by n3roGit** [comment]
Hi Dylantje,
i have never tested this code. But you could try this:

https://forum.pimatic.org/topic/383/tips-battery-powered-sensors

after this settings your arduino consumes minimal current :)
